### ISSUE TITLE
Operation status API should return 202 when underlying operation result is not available

### ISSUE THREAD

**Issue by jesspanni** [marain-dotnet/Marain.Operations#26]
The operation status API currently returns a 200 response. This status code indicates to clients that no further action is required or available to take.  In practice clients will often want to periodically check the status of the long running operation until the operation result is available. 

If the operation status API were to return a 202 while the underlying operation result is not finalized then this would give clients the opportunity to automatically poll the endpoint until such time as a result is available. The location header of the response could then be set to itself to ensure intent is clear.

**Comment by mwadams** [comment]
I think this is a good choice.

We should update before we get too many dependencies.

**Comment by mwadams** [comment]
In fact, the API does not correctly implement the specification.

It should return a 202 Accepted until the operation is complete, whereupon it should run a 200 OK.

**Comment by HowardvanRooijen** [comment]
This seems different to the original Operations API which was 202 based: https://marain.io/swagger/ui/index#/Operations

**Comment by mwadams** [comment]
@HowardvanRooijen  is right - but that wasn't conformant either.

The "GET" operation should only return 200 when the operation is complete, otherwise it should return 202.

**Comment by mwadams** [comment]
Closed by #27
